# Generated by Django 5.1 on 2024-08-29 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='abacusapp.asset')),
            ],
        ),
    ]
