# Generated by Django 5.1 on 2024-08-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacusapp', '0002_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAssetQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacusapp.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacusapp.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'asset')},
            },
        ),
    ]
