# Generated by Django 5.1 on 2024-08-29 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacusapp', '0003_portfolioassetquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='abacusapp.asset'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('asset', 'date')},
        ),
    ]
