# Generated by Django 5.1 on 2024-08-30 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacusapp', '0010_alter_portfolioasset_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioasset',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacusapp.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abacusapp.portfolio')),
            ],
        ),
    ]
