# Generated by Django 5.1 on 2024-08-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abacusapp', '0011_alter_portfolioasset_weight_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioasset',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
