services:
  web:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    entrypoint: python3 manage.py runserver 0.0.0.0:8000
    # entrypoint: bash
    volumes:
      - ../.:/app
    # working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
